### ISSUE TITLE
Expose internal width and height of the current authentication UI "screen"

### ISSUE THREAD

**Issue by jason-dgio** [polina-c/flutter-auth-ui#12]
This would be very handy when implementing and sizing custom UI around FAUI.

**Comment by polina-c** [comment]
Jason, I updated the lib to not enforce any sizes. All the sized are defined by the custom builder or taken from the context or from default palette, defined in your app. Check the class DefaultScreenBuilder.
When you pass your builder, it can define all the sizes.
Does it make sense?
