### ISSUE TITLE
No automatic signin? 

### ISSUE THREAD

**Issue by emailsubjekt** [polina-c/flutter-auth-ui#14]
Hi, I'm just writing to thank you for writing this project. I was just wondering will you be implementing automatic sign-in too?

**Comment by polina-c** [comment]
@emailsubjekt , thank you for creating the bug!

Automatic sign in is already implemented and is named 'silent sign in'.
Could you please recommend a change in documentation to make the feature easier discoverable for people like you?

You can check how the feature works at https://flatter-auth-ui-demo1.codemagic.app/#/

Here is the steps:

1. Open the link
2. Sign in 
3. Close browser
4. Open the link again
It is expected that you will be signed in automatically.

If it does not work for you, please, create bug with the details like what browser you use.
