### ISSUE TITLE
Recommended database rule setting?

### ISSUE THREAD

**Issue by MostHated** [polina-c/flutter-auth-ui#31]
Hello,
    Right now I have my furebase db rules setup as seen below, but I am not sure if this is considered sufficient, or what a more secure and typical example might look like that would work for a system like this.

I am wondering if anyone happens to have any sort of recommended database rule set for this/allowing a user to save data to their own "users" document? (/users/{userId})

Thanks, 
-MH

```css
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth.uid != null;
    }
  }
}
```

**Comment by polina-c** [comment]
Looks good for me. However, I am not security specialist. I recommend to post this question on stackoverflow, and tag with 'firestore' so that firebase security specialists get nitified.
